num1 = float(input("Enter first number: "))
num2 = float(input("Enter second number: "))
sum_result = num1 + num2
diff_result = num1 - num2
prod_result = num1 * num2
div_result = num1 / num2
int_div_result= num1 // num2  #Integer division
mod_result= num1 % num2       #Modulus
print(f"Sum: {num1} + {num2} = {sum_result} ")
print(f"Difference: {num1} - {num2} = {diff_result} ")
print(f"Product: {num1} * {num2} = {prod_result} ")
print(f"Quotient: {num1} / {num2} = {div_result} ")
print(f"Integer Quotient: {num1} // {num2} = {int_div_result} ")
print(f"Remainder: {num1} % {num2} = {mod_result} ") 